routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\OrderController;
// use App\Http\Controllers\HomeController;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Auth::routes();


Route::get('/', function () {
    return view('welcome');
});




Route::get('orders/delete/{id}','OrdersController@destroy')->name('order.delete');
Route::get('myOrders', 'OrdersController@myOrders')->name('orders.myOrders')->middleware('auth');
Route::get('statusdone', 'OrdersController@statusDone')->name('orders.statusDone')->middleware('auth');
Route::get('statuscancel', 'OrdersController@statusCancel')->name('orders.statusCancel')->middleware('auth');
// Route::get('backPage', 'OrdersController@backPage')->middleware('auth');
Route::resource('users', 'UsersController')->middleware('auth');
Route::get('orders/edit/{id}','OrdersController@edit')->name('order.edit');

Route::get('orders', 'OrdersController@index')->name('orders.index')->middleware('auth');

// Route::get('/home', [HomeController::class, 'index'])->name('home');
// Route::get('/home', 'App\Http\Controllers\HomeController@index')->name('home');
Route::get('/home',[
    'uses'=>'HomeController@index',
    'as'=>'home',
    
            ]);

 Route::resource('orders', 'OrdersController')->middleware('auth');

 Route::get('orders/changestatus/{cid}/{sid}', 'OrdersController@changeStatus')->name('orders.changestatus')->middleware('auth');

//  Route::post('/backPage', function () {
//     // Validate the request...

//     return back()->withInput();
// });


            

app/Order.php
<?php

namespace App;

// use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Order extends Model
{
    protected $fillable = [
        'model','address','totalPrice','isPaid','telephone','deliveryDate','user_id','status_id','product_id'
    ];

    public function owner(){
        return $this->belongsTo('App\User','user_id');
    }

    public function own(){
        return $this->belongsTo('App\Product','product_id');
    }

    public function status()
    {
        return $this->belongsTo('App\Status');
    } 
}

app/Http/Controllers/OrdersController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\User;
use App\Product;
use App\Order;
use App\Status;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Gate;
use Illuminate\Support\Facades\Session;
use Illuminate\Support\Facades\DB;

class OrdersController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $orders = Order::with('owner','own')->where([['status_id','!=', '4'],['status_id','!=', '5']])->orderBy('deliveryDate')->paginate(5);
        $users = User::all();
        $statuses = Status::all();
        return view('Orders.index', compact('orders','users','statuses')); 
    }
    public function myOrders()
    {        
        $userId = Auth::id();
        $user = User::findOrFail($userId);
        $orders =   Order::with('owner')->where([['user_id', $userId],['status_id','!=', '4'],['status_id','!=', '5']])->paginate(5);
        // $orders = $user->orders;
        $users = User::all();
        //statuses = Status::all();        
        return view('Orders.index', compact('orders','users'));
    }

    public function statusDone()
    {        
        $userId = Auth::id();
        $user = User::findOrFail($userId);
        $orders =   Order::with('owner')->where('status_id', '4')->paginate(5);
        // $orders = $user->orders;
        $users = User::all();
        $statuses = Status::all();        
        return view('Orders.index', compact('orders','users','statuses'));
    }

    public function statusCancel()
    {        
        $userId = Auth::id();
        $user = User::findOrFail($userId);
        $orders =   Order::with('owner')->where('status_id', '5')->paginate(5);
        // $orders = $user->orders;
        $users = User::all();
        $statuses = Status::all();        
        return view('Orders.index', compact('orders','users','statuses'));
    }

    public function changeUser($cid, $uid = null){
        Gate::authorize('assign-user');
        $order = Order::findOrFail($cid);
        $order->user_id = $uid;
        $order->save(); 
        return back();

    }

    public function changeStatus($cid, $sid)
    {
        $order = Order::findOrFail($cid);
        if(Gate::allows('change-status', $order))
        {
            $from = $order->status->id;
            if(!Status::allowed($from,$sid)) return redirect('orders');        
            $order->status_id = $sid;
            $order->save();
        }else{
            Session::flash('notallowed', 'You are not allowed to change the status of the user becuase you are not the owner of the user');
        }
        return back();
        
    }
    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $orders = Order::all();
        // $product = Product::all();
        $users = User::all();
        $products = Product::all();
        $id=Auth::id();
        $user_name = DB::table('users')->where('id', $id)->first();
        // return view('orders.create', compact('orders','users','products' ));
        return view('Orders.create', compact('orders','users','user_name','products' ));

    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $order = new Order();
        
        $order->model = $request->model;
        $order->address = $request->address;
        $order->totalPrice = $request->totalPrice;
        $order->isPaid = $request->isPaid;
        $order->deliveryDate = $request->deliveryDate;
        $order->telephone = $request->telephone;
        $order->user_id = $request->user_selected;
        $order->product_id = $request->product_selected;
        $order->customer = $request->customer;
        $order->remarks = $request->remarks;
        $order->save();
        return redirect('orders');
        // return back();
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $orders = Order::findOrFail($id);
        return view('Orders.show', ['orders' => $orders]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        
        $order = Order::findOrFail($id);
        $users = User::all();
        $products = Product::all();
        return view('Orders.edit', compact('order', 'products', 'users'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $order = Order::findOrFail($id);
        $order->model = $request->model;
        $order->address = $request->address;
        $order->totalPrice = $request->totalPrice;
        $order->isPaid = $request->isPaid;
        $order->telephone = $request->telephone;
        $order->customer = $request->customer;
        $order->remarks = $request->remarks;
        $order->deliveryDate = $request->deliveryDate;

        $order->update($request->all());// update all data
        return redirect()->route('orders.index')->with('success', 'Data Updated');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $order = Order::findOrFail($id);
        $order->delete();
        return redirect('Orders')->with('message','The Order has been Removed');
    }
}

resources/views/Orders/create.blade.php
@extends('layouts.sidebar')

@section('title','Orders')

@section('content')
       <h1>Create Order</h1>
        <form method='post' action="{{action('OrdersController@store')}}">
        @csrf 

        <!-- <div class="form-group">
            <label for = "customer">customer</label>
            <input type = "text" class="form-control" name = "customer">
        </div> -->
        <div class="form-group">
            <label for = "product">Product</label>
            <select class="form-control" id="selectProduct" name="product_selected" required focus>
            
    @foreach($products as $product)
    <option value="{{$product->id}}">{{ $product->name }}</option>
    @endforeach
  </select>
           
        </div>
        <div class="form-group">
            <label for = "model">Engine Code</label>
            <input type = "text" class="form-control" name = "model" required >
        </div>
        <div class="form-group">
            <label for = "customer">Customer</label>
            <input type = "text" class="form-control" name = "customer" required >
        </div>

        <div class="form-group">
            <label for = "address">Address</label>
            <input type = "text" class="form-control" name = "address" required >
        </div>
        <div class="form-group">
            <label for = "totalPrice">Price Without TAX</label>
            <input type = "number" class="form-control" name = "totalPrice" required >
        </div>
        <div class="form-group">
            <label for = "isPaid">Paid?</label>
            <input type = "text" class="form-control" name = "isPaid" required >
        </div>
        <div class="form-group">
            <label for = "telephone">Telephone</label>
            <input type = "number" class="form-control" name = "telephone" required >
        </div>
        <div class="form-group">
            <label for = "date">Delivery Date</label>
            <input type="date" name="deliveryDate" id="date" class="form-control" value="{{ date("d-m-y") }}" required >
        </div>
        <div class="form-group">
            <label for = "remarks">Remarks</label>
            <input type = "text" class="form-control" name = "remarks" >
        </div>
        <div class="form-group">
            <label for = "userid">User</label>
            <select class="form-control" id="selectUser" name="user_selected" required focus>
            
    @foreach($users as $user)
    <option value="{{$user->id}}" @if ($user->id == $user_name->id) selected @endif>{{ $user->name }}</option>
    @endforeach
  </select>
          
        </div> 


         <div class="form-group">
            <input type="submit" class="btn btn-success btn-block" name="submit" value="Save">
        </div>                     
        </form>  


@endsection

resources/views/Orders/edit.blade.php
@extends('layouts.sidebar')
@section('content')

<h1>Edit a order</h1>
<form method='post' action="{{action('OrdersController@update', $order->id)}}">
  @csrf
  @method('PATCH')

 

<div class="form-group">
    <div class="col-md-2">
      <label class="control-label" for="model"> Engine Code </label></div>
    <div class="col-md-10">
      <input type="text" class="form-control" name="model" value="{{$order->model}}">
    </div>

    <div class="form-group">
    <div class="col-md-2">
      <label class="control-label" for="customer"> Customer </label></div>
    <div class="col-md-10">
      <input type="text" class="form-control" name="customer" value="{{$order->customer}}">
    </div>

    <div class="form-group">
    <div class="col-md-2">
      <label class="control-label" for="Address"> Address </label></div>
    <div class="col-md-10">
      <input type="text" class="form-control" name="address" value="{{$order->address}}">
    </div>

        <div class="form-group">
    <div class="col-md-2">
      <label class="control-label" for="totalPrice">Price Without TAX</label></div>
    <div class="col-md-10">
      <input type="number" class="form-control" name="totalPrice" value="{{$order->totalPrice}}">
    </div>

    <div class="form-group">
    <div class="col-md-2">
      <label class="control-label" for="isPaid"> Paid? </label></div>
    <div class="col-md-10">
      <input type="text" class="form-control" name="isPaid" value="{{$order->isPaid}}">
    </div>

        <div class="form-group">
    <div class="col-md-2">
      <label class="control-label" for="telephone"> Telephone </label></div>
    <div class="col-md-10">
      <input type="number" class="form-control" name="telephone" value="{{$order->telephone}}">
    </div>

    <div class="form-group">
    <div class="col-md-2">
      <label class="control-label" for="deliveryDate"> Date </label></div>
    <div class="col-md-10">
      <input type="date" class="form-control" name="deliveryDate" value="{{$order->deliveryDate}}">
    </div>


    <div class="form-group">
    <div class="col-md-2">
      <label class="control-label" for="remarks"> Remarks </label></div>
    <div class="col-md-10">
      <input type="text" class="form-control" name="remarks" value="{{$order->remarks}}">
    </div>
  
   
  </div>

  <div class="col-md-8">
    <div class="form-group">
      <input type="submit" class="btn btn-success btn-block" name="submit" value="Save Changes">
    </div>
  </div>
</form>




@endsection

resources/views/Orders/index.blade.php
@extends('layouts.sidebar')

@section('title','Orders')

@section('content')

@if(Session::has('notallowed'))
<div class='alert alert-danger'>
    {{Session::get('notallowed')}}
</div>

@endif
         @if (Session::has('message'))
            <div class="alert alert-success">{{Session::get('message')}} </div>
        @endif

    
    @if (Request::is('myOrders')) 
        <h1 title='My order' style="float: left;"><b>My Orders</b></h1> 
        <h1 title='Add a new order' style="float: right;"><b><a href="{{ url('orders/create') }}">+</a></b></h1> 
        <br></br>
        <br></br>
        <h6><a  href="{{action('OrdersController@index')}}">Show All Orders</a></h6>   
    @else
        <h1 title='All order' style="float: left;"><b>All Orders</b></h1>
        <h1 title='Add a new order' style="float: right;"><b><a href="{{ url('orders/create') }}">+</a></b></h1>
        <br></br>
        <br></br>
        <h6><a href="{{ url('myOrders') }}">Show My Orders</a></h6>

    @endif
  
    

    <!-- <div class="panel-heading">
@if (Request::is('myOrders')) 
<h3 class="panel-title" >My Orders</h3>
@endif
</div> -->
    <div class="table-responsive">
    <table class="table align-items-center table-flush" >
            <tr>
            <th>Id</th><th>Seller</th><th>Customer</th><th>Product</th><th>Engine Code</th><th>Address</th><th>Price</th><th>Total Price</th><th>Is Paid?</th><th>Delivery Date</th><th>Status Order</th><th>Edit</th><th>More Details</th>
              
            </tr>
        <!-- the table data -->
            @foreach($orders as $order)
                   
            <tr>
            <td> {{$order->id}}</td>
            <td>
                <div class="dropdown">
                    <!-- <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"> -->
                        @if(isset($order->user_id))
                          {{$order->owner->name}}  
                        @else
                          Assign owner
                        @endif
                    </button>
                  
                  </div> 
            </td>  
            <td>{{$order->customer}}</td>             
            <td> @if(isset($order->product_id))
                          {{$order->own->name}}  
                        @else
                          Assign own
                        @endif</td>
            <td> {{$order->model}}</td> 
            <td> {{$order->address}}</td>
            <td> {{$order->totalPrice}}</td>
            <td> {{$order->totalPrice * 1.17}}</td>
            <td> {{$order->isPaid}}
            <td> {{$order->deliveryDate}}</td>
            <td>
                <div class="dropdown">
                    @if (null != App\Status::next($order->status_id))    
                    <button class="dropdown-toggle" style="background:#99e6e6" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        @if (isset($order->status_id))
                           {{$order->status->name}}
                        @else
                            Define status
                        @endif
                    </button>
                    @else 
                    {{$order->status->name}}
                    @endif
                                                   
                    @if (App\Status::next($order->status_id) != null )
                    <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                        @foreach(App\Status::next($order->status_id) as $status)
                         <a class="dropdown-item" href="{{route('orders.changestatus', [$order->id,$status->id])}}">{{$status->name}}</a>
                        @endforeach                               
                    </div>
                    @endif
                </div>                            
            </td>
            <td><a class="badge badge-info " style="background:#99e6e6" href = "{{route('orders.edit',$order->id)}}">Edit</a></td>
            <td> <a class="badge badge-info " style="background:#99e6e6" href="{{ route('orders.show',$order->id) }}"> Click Here </a> </td>
           

        </tr>
            @endforeach
    </table>

    {{$orders->links()}}
@endsection

resources/views/Orders/show.blade.php
@extends('layouts.sidebar')
@section('content')
    
<div class="w3-sidebar w3-bar-block " style="margin: 0 0 5% 0;" >
         
         <div class="sidebar-module" style="font-family: Arial Black, Gadget, sans-serif;">
           <ol class="list-unstyled">
            
           
             
          </ol>
        
                
 </div>

 <div class="panel panel-default">

<br>
<div class="table-responsive">
<table  class="table table-striped table-bordered">
       <thead>
        <tr>
        <th style="text-align:center">Id </th>
         <th style="text-align:center">Phone</th>
         <th style="text-align:center">Remarks</th>
         <th style="text-align:center">Created</th>
         <th style="text-align:center">Updated</th>
         
       
        </tr>
       </thead>
       <tbody>
    
  <tr>
  <td> {{$orders->id}}</td>
  <td> {{$orders->telephone}}</td>
  <td> {{$orders->remarks}}</td>
  <td> {{$orders->created_at}}</td>
  <td> {{$orders->updated_at}}</td>        

</tr>


       </tbody>
      </table>
</div>
</div>

</div>

 
 @endsection
<!-- <footer class="ttt">Website of EISS</footer> 

<style>

 

  .col {
    position: absolute;
    top: 87px;
    left: 750px;
  }

.ttt{
   position:absolute;
   bottom:0;
   width:100%;
   height:30px;   
   background:#6cf;
   text-align:center;
}

</style>

-->